# docker-compose.yml
version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - "./api/.env"

  db-admin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    env_file:
      - "./api/.env"
    depends_on:
      - db
    volumes:
      - ./deploy/pgadmin4/servers.json:/pgadmin4/servers.json

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3000"
    env_file:
      - "./api/.env"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
