# docker-compose.yml
version: "3"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - ".env"
    ports:
      - "5432:5432"

  db-admin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ".env"
    ports:
      - "5050:80"
